name: Deploy Lambda Function

on:
  push:
    branches:
      [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: modulos/actions-zip@v1
      - name: Zip Lambda Function
        run: zip -r code.zip .
      - name: AWS CLI v2
        run: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
              --function-name arn:aws:lambda:ap-southeast-2:249133131535:function:TestCICDFunction \
              --zip-file fileb://code.zip"
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-2